// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMdcXxOd4mBanmYainTfDVNijTeNcly9M',
    appId: '1:264110979122:web:f32b32927f4ab92a46642b',
    messagingSenderId: '264110979122',
    projectId: 'client-follow-up-app-eb46b',
    authDomain: 'client-follow-up-app-eb46b.firebaseapp.com',
    storageBucket: 'client-follow-up-app-eb46b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKRz8Lk4u2Esp-Mlrh1czIoXyukR28yg',
    appId: '1:264110979122:android:617bf13b688fb36b46642b',
    messagingSenderId: '264110979122',
    projectId: 'client-follow-up-app-eb46b',
    storageBucket: 'client-follow-up-app-eb46b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaGPm8jVuKj-Ab8wgXPNiNddh5v2vX-0M',
    appId: '1:264110979122:ios:cf4f3c33fd1a2d9b46642b',
    messagingSenderId: '264110979122',
    projectId: 'client-follow-up-app-eb46b',
    storageBucket: 'client-follow-up-app-eb46b.firebasestorage.app',
    iosBundleId: 'com.example.clientFollowUpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaGPm8jVuKj-Ab8wgXPNiNddh5v2vX-0M',
    appId: '1:264110979122:ios:cf4f3c33fd1a2d9b46642b',
    messagingSenderId: '264110979122',
    projectId: 'client-follow-up-app-eb46b',
    storageBucket: 'client-follow-up-app-eb46b.firebasestorage.app',
    iosBundleId: 'com.example.clientFollowUpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMdcXxOd4mBanmYainTfDVNijTeNcly9M',
    appId: '1:264110979122:web:ad1c34426595fbf046642b',
    messagingSenderId: '264110979122',
    projectId: 'client-follow-up-app-eb46b',
    authDomain: 'client-follow-up-app-eb46b.firebaseapp.com',
    storageBucket: 'client-follow-up-app-eb46b.firebasestorage.app',
  );
}
